### ISSUE TITLE
Error after upgrading 

### ISSUE THREAD

**Issue by dominch** [jrupesh/redmine_query_share#2]
hello, 
after upgrade from git it stopped to work with redmine 2.6

<pre>
undefined method `update_query_from_params' for class `QueriesController'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'
/var/data/redmine_test/plugins/redmine_query_share/lib/query_share/patches/queries_controller_patch.rb:11:in `block in included'
/var/data/redmine_test/plugins/redmine_query_share/lib/query_share/patches/queries_controller_patch.rb:9:in `class_eval'
/var/data/redmine_test/plugins/redmine_query_share/lib/query_share/patches/queries_controller_patch.rb:9:in `included'
/var/data/redmine_test/plugins/redmine_query_share/lib/query_share/patches/queries_controller_patch.rb:29:in `include'
/var/data/redmine_test/plugins/redmine_query_share/lib/query_share/patches/queries_controller_patch.rb:29:in `<top (required)>'
</pre>

**Comment by dominch** [comment]
Thanks for quick fix, it's working now! :)
